
export const imgHelper = {
	'analytics': '/analytics.png',
	'availability': '/availability.png',
	'candidates': '/candidates.png',
	'client': '/client.png',
	'company': '/company.png',
	'home': '/home.png',
	'experience': '/experience.png',
	'gender': '/gender.png',
	'help': '/help.png',
	'jobRole': '/jobRole.png',
	'location': '/location.png',
	'logout': '/logout.png',
	'lpa': '/lpa.png',
	'martial': '/martial.png',
	'preferredJob': '/preferredJob.png',
	'qualification': '/qualification.png',
	'recruitment': '/recruitment.png',
	'resume': '/resume.png',
	'seertechsystemsLogo': '/seertechsystems_logo.jpeg',
	'settings': '/settings.png',
	'userProfile': '/userProfile.png',
	'edit': '/edit.png',
	'calendar': '/calendar.png',
	'job': '/job.png',
	'jobExperience': '/jobExp.png',
	'jobBudget':'/rupee.png',
	'insertedBy': '/insertedBy.png',
	'seertech': '/seertechLogo.png',
	'google': '/google-logo.png',
}