import type { InvoiceTemplate } from "../invoice"

export const defaultInvoiceTemplate: InvoiceTemplate = {
  id: "default-invoice",
  name: "Standard Invoice",
  themeId: "modern-clean",
  sections: [
    {
      id: "company-info",
      title: "Company Information",
      fields: [
        {
          id: "company_name",
          label: "Company Name",
          type: "text",
          required: true,
          placeholder: "Enter your company name",
          styleForm: {
            width: "100%",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontWeight: "600",
            fontSize: "1.125rem",
            color: "#059669",
          },
        },
        {
          id: "company_address",
          label: "Company Address",
          type: "textarea",
          placeholder: "Enter your company address",
          styleForm: {
            width: "100%",
            height: "4rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#6b7280",
          },
        },
      ],
    },
    {
      id: "client-info",
      title: "Client Information",
      fields: [
        {
          id: "client_name",
          label: "Client Name",
          type: "text",
          required: true,
          placeholder: "Enter client name",
          styleForm: {
            width: "100%",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontWeight: "600",
            fontSize: "1rem",
          },
        },
        {
          id: "client_email",
          label: "Client Email",
          type: "email",
          placeholder: "client@example.com",
          styleForm: {
            width: "100%",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#6b7280",
          },
        },
      ],
    },
    {
      id: "invoice-details",
      title: "Invoice Details",
      fields: [
        {
          id: "invoice_number",
          label: "Invoice Number",
          type: "text",
          required: true,
          placeholder: "INV-001",
          styleForm: {
            width: "200px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontWeight: "600",
            color: "#059669",
          },
        },
        {
          id: "invoice_date",
          label: "Invoice Date",
          type: "date",
          required: true,
          styleForm: {
            width: "200px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontWeight: "500",
          },
        },
        {
          id: "amount",
          label: "Total Amount",
          type: "number",
          required: true,
          placeholder: "0.00",
          styleForm: {
            width: "150px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontWeight: "700",
            fontSize: "1.25rem",
            color: "#059669",
          },
        },
      ],
    },
  ],
}

export const professionalInvoiceTemplate: InvoiceTemplate = {
  id: "professional-invoice",
  name: "Professional Invoice (SEERTECH Style)",
  themeId: "professional-red",
  sections: [
    {
      id: "header-section",
      title: "Invoice Header",
      fields: [
        {
          id: "invoice_title",
          label: "Invoice Title",
          type: "text",
          required: true,
          placeholder: "Invoice",
          order: 1,
          styleForm: {
            width: "200px",
            height: "3rem",
            padding: "0.75rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
            fontSize: "1.125rem",
            fontWeight: "600",
          },
          styleDisplay: {
            fontSize: "2.5rem",
            fontWeight: "700",
            color: "#dc2626",
            textTransform: "uppercase",
            letterSpacing: "0.05em",
            marginBottom: "2rem",
          },
        },
      ],
    },
    {
      id: "company-section",
      title: "Company Details",
      fields: [
        {
          id: "company_name",
          label: "Company Name",
          type: "text",
          required: true,
          placeholder: "SEERTECH SYSTEMS",
          order: 2,
          styleForm: {
            width: "100%",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1.25rem",
            fontWeight: "700",
            color: "#dc2626",
            marginBottom: "0.5rem",
          },
        },
        {
          id: "company_address",
          label: "Registered Address",
          type: "textarea",
          placeholder: "Ramaniyam Marvel, No B27, Seshadripuram...",
          order: 3,
          styleForm: {
            width: "100%",
            height: "5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#374151",
            lineHeight: "1.5",
            marginBottom: "1rem",
          },
        },
        {
          id: "gst_number",
          label: "GST Number",
          type: "text",
          placeholder: "33AFBFS0880G1Z6",
          order: 4,
          styleForm: {
            width: "250px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#374151",
            fontWeight: "500",
          },
        },
      ],
    },
    {
      id: "client-section",
      title: "Client Information",
      fields: [
        {
          id: "client_name",
          label: "Invoice To",
          type: "text",
          required: true,
          placeholder: "Global ESG Solutions Pvt Ltd",
          order: 5,
          styleForm: {
            width: "100%",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1.125rem",
            fontWeight: "600",
            color: "#dc2626",
            marginBottom: "0.5rem",
          },
        },
        {
          id: "client_address",
          label: "Client Address",
          type: "textarea",
          placeholder: "Client address details...",
          order: 6,
          styleForm: {
            width: "100%",
            height: "4rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#374151",
            lineHeight: "1.5",
          },
        },
        {
          id: "client_gst",
          label: "Client GST No",
          type: "text",
          placeholder: "27AAUFP0997K2Z9",
          order: 7,
          styleForm: {
            width: "250px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#374151",
            fontWeight: "500",
          },
        },
      ],
    },
    {
      id: "invoice-info",
      title: "Invoice Information",
      fields: [
        {
          id: "invoice_number",
          label: "Invoice Number",
          type: "text",
          required: true,
          placeholder: "IV003324",
          order: 8,
          styleForm: {
            width: "200px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1rem",
            fontWeight: "600",
            color: "#374151",
          },
        },
        {
          id: "invoice_date",
          label: "Invoice Date",
          type: "date",
          required: true,
          order: 9,
          styleForm: {
            width: "200px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1rem",
            fontWeight: "500",
            color: "#374151",
          },
        },
        {
          id: "due_date",
          label: "Due Date",
          type: "date",
          order: 10,
          styleForm: {
            width: "200px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1rem",
            fontWeight: "500",
            color: "#374151",
          },
        },
      ],
    },
    {
      id: "project-section",
      title: "Project Details",
      fields: [
        {
          id: "project_name",
          label: "Project/Service",
          type: "text",
          placeholder: "Contract Hiring: QA Specialist",
          order: 11,
          styleForm: {
            width: "100%",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1.125rem",
            fontWeight: "600",
            color: "#dc2626",
            marginBottom: "0.5rem",
          },
        },
        {
          id: "candidate_name",
          label: "Candidate Name",
          type: "text",
          placeholder: "Venkataramana Sarayavalasa",
          order: 12,
          styleForm: {
            width: "100%",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1rem",
            fontWeight: "500",
            color: "#374151",
          },
        },
        {
          id: "requirement",
          label: "Requirement",
          type: "text",
          placeholder: "QA",
          order: 13,
          styleForm: {
            width: "300px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1rem",
            color: "#374151",
          },
        },
        {
          id: "description",
          label: "Description",
          type: "textarea",
          placeholder:
            "Venkataramana Sarayavalasa - September 2024 Billing\nPer Hour Billing Rate: $9\nNo of hours billed - 48 hours",
          order: 14,
          styleForm: {
            width: "100%",
            height: "6rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#374151",
            lineHeight: "1.6",
            whiteSpace: "pre-line",
          },
        },
      ],
    },
    {
      id: "billing-section",
      title: "Billing Details",
      fields: [
        {
          id: "total_value",
          label: "Total Value",
          type: "number",
          placeholder: "432.00",
          order: 15,
          styleForm: {
            width: "150px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1rem",
            fontWeight: "600",
            color: "#374151",
          },
        },
        {
          id: "percentage_billed",
          label: "% Billed",
          type: "number",
          placeholder: "100.00",
          order: 16,
          styleForm: {
            width: "120px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1rem",
            color: "#374151",
          },
        },
        {
          id: "invoice_value",
          label: "Invoice Value",
          type: "number",
          placeholder: "432.00",
          order: 17,
          styleForm: {
            width: "150px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1.25rem",
            fontWeight: "700",
            color: "#dc2626",
          },
        },
        {
          id: "currency",
          label: "Currency",
          type: "select",
          placeholder: "USD",
          order: 18,
          styleForm: {
            width: "100px",
            height: "2.5rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "1rem",
            fontWeight: "500",
            color: "#374151",
          },
        },
      ],
    },
    {
      id: "payment-section",
      title: "Payment Information",
      fields: [
        {
          id: "payment_terms",
          label: "Payment Terms",
          type: "textarea",
          placeholder: "Payment to be cleared within 15 days from invoice date",
          order: 19,
          styleForm: {
            width: "100%",
            height: "4rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#374151",
            lineHeight: "1.5",
            marginBottom: "1rem",
          },
        },
        {
          id: "bank_details",
          label: "Bank Details",
          type: "textarea",
          placeholder:
            "Account Name: SEERTECH SYSTEMS\nBank Name: HDFC Bank Ltd\nAccount Number: 50200093362667\nBranch: Egmore, Chennai, 600008\nHDFC Swift Code: HDFCINBBCHE",
          order: 20,
          styleForm: {
            width: "100%",
            height: "8rem",
            padding: "0.5rem",
            borderRadius: "0.375rem",
            border: "1px solid #d1d5db",
          },
          styleDisplay: {
            fontSize: "0.875rem",
            color: "#374151",
            lineHeight: "1.6",
            whiteSpace: "pre-line",
            backgroundColor: "#f9fafb",
            padding: "1rem",
            borderRadius: "0.375rem",
          },
        },
      ],
    },
  ],
}

export const professionalRedTheme = {
  id: "professional-red",
  name: "Professional Red",
  type: "template" as const,
  cssProperties: {
    backgroundColor: "#fef2f2",
    color: "#374151",
    fontFamily: "system-ui, -apple-system, sans-serif",
    padding: "2rem",
    borderRadius: "0.5rem",
    border: "1px solid #e5e7eb",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
  },
}

export const allInvoiceTemplates = [defaultInvoiceTemplate, professionalInvoiceTemplate]
