import type { ThemeConfig } from "../invoice"

export const defaultThemes: ThemeConfig[] = [
  {
    id: "modern-clean",
    name: "Modern Clean",
    type: "template",
    styles: {
      backgroundColor: "#ffffff",
      color: "#475569",
      fontWeight: "400",
      padding: "1rem",
      borderRadius: "0.5rem",
      border: "1px solid #e2e8f0",
    },
    isDefault: true,
  },
  {
    id: "professional-red",
    name: "Professional Red",
    type: "template",
    styles: {
      backgroundColor: "#fef2f2",
      color: "#374151",
      fontWeight: "400",
      padding: "2rem",
      borderRadius: "0.5rem",
      border: "1px solid #e5e7eb",
      boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    },
  },
  {
    id: "professional-emerald",
    name: "Professional Emerald",
    type: "template",
    styles: {
      backgroundColor: "#f0fdf4",
      color: "#065f46",
      fontWeight: "500",
      padding: "1.5rem",
      borderRadius: "0.75rem",
      border: "2px solid #059669",
    },
  },
  {
    id: "minimal-gray",
    name: "Minimal Gray",
    type: "template",
    styles: {
      backgroundColor: "#f8fafc",
      color: "#334155",
      fontWeight: "400",
      padding: "1rem",
      borderRadius: "0.25rem",
      border: "1px solid #cbd5e1",
    },
  },
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    type: "template",
    styles: {
      backgroundColor: "#eff6ff",
      color: "#1e40af",
      fontWeight: "500",
      padding: "1.5rem",
      borderRadius: "0.5rem",
      border: "2px solid #3b82f6",
    },
  },
  {
    id: "warm-orange",
    name: "Warm Orange",
    type: "template",
    styles: {
      backgroundColor: "#fff7ed",
      color: "#c2410c",
      fontWeight: "500",
      padding: "1.25rem",
      borderRadius: "0.75rem",
      border: "2px solid #f97316",
    },
  },
  {
    id: "elegant-purple",
    name: "Elegant Purple",
    type: "template",
    styles: {
      backgroundColor: "#faf5ff",
      color: "#7c2d92",
      fontWeight: "500",
      padding: "1.5rem",
      borderRadius: "0.5rem",
      border: "2px solid #a855f7",
    },
  },
  {
    id: "sunset-red",
    name: "Sunset Red",
    type: "template",
    styles: {
      backgroundColor: "#fef2f2",
      color: "#b91c1c",
      fontWeight: "500",
      padding: "1.25rem",
      borderRadius: "0.5rem",
      border: "2px solid #ef4444",
    },
  },
  {
    id: "ocean-teal",
    name: "Ocean Teal",
    type: "template",
    styles: {
      backgroundColor: "#f0fdfa",
      color: "#0f766e",
      fontWeight: "500",
      padding: "1.5rem",
      borderRadius: "0.75rem",
      border: "2px solid #14b8a6",
    },
  },
  {
    id: "golden-yellow",
    name: "Golden Yellow",
    type: "template",
    styles: {
      backgroundColor: "#fefce8",
      color: "#a16207",
      fontWeight: "500",
      padding: "1.25rem",
      borderRadius: "0.5rem",
      border: "2px solid #eab308",
    },
  },
  {
    id: "dark-slate",
    name: "Dark Slate",
    type: "template",
    styles: {
      backgroundColor: "#0f172a",
      color: "#e2e8f0",
      fontWeight: "400",
      padding: "1.5rem",
      borderRadius: "0.5rem",
      border: "2px solid #475569",
    },
  },
  {
    id: "soft-pink",
    name: "Soft Pink",
    type: "template",
    styles: {
      backgroundColor: "#fdf2f8",
      color: "#be185d",
      fontWeight: "500",
      padding: "1.25rem",
      borderRadius: "0.75rem",
      border: "2px solid #ec4899",
    },
  },
  {
    id: "field-highlight",
    name: "Highlight Field",
    type: "field",
    styles: {
      backgroundColor: "#ecfdf5",
      color: "#065f46",
      fontWeight: "600",
      padding: "0.75rem",
      borderRadius: "0.5rem",
      border: "2px solid #10b981",
    },
  },
  {
    id: "field-subtle",
    name: "Subtle Field",
    type: "field",
    styles: {
      backgroundColor: "#f1f5f9",
      color: "#475569",
      fontWeight: "400",
      padding: "0.5rem",
      borderRadius: "0.25rem",
      border: "1px solid #e2e8f0",
    },
  },
]
